[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
blog_dapp = "F3Q3sRSup4zWtezFtcuzhhBFh3UGDkDdeEfo5d8aRq9z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/rishabhjaiswal/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
